language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t deepud26/docker-react -f Dockerfile.dev .

script:
  - docker run  -e CI=true deepud26/docker-react npm run build
